# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Green Guard add-on
version: "1.0.0"
slug: greenguard
description: Green Guard add-on
url: "https://github.com/beaTejakulator/green-guard/tree/main/green-guard"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/beatejakulator/{arch}-green-guard"
